baseURL = "https://blog.danevan.top/"
theme = "hermit-v2"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

title = "Dan_EvanのBlog"
copyright = "Dan_Evan"

pygmentsCodefences = true
pygmentsUseClasses = true

rssLimit = 10

[params.author]
  name = "Dan_Evan"
  about = "about.md"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "这里是Dan_Evan的个人博客，基于Hugo框架搭建，CF Pages部署"
  themeColor = "#494f5c"
  accentColor = "#018472"

  homeSubtitle = "记录我的笔记和日常发癫，。"
  footerCopyright = "Dan_Evan"
  justifyContent = false
  code_copy_button = true
  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = true
  shareSocial = true

  [params.pages]
    LastmodOpen = '['
    LastmodClose = ']'
    readTimeSeparator = "… ⏱ 阅读时长:"
    lastUpdatedOn = "最后更新于: "
    relatedPosts = true

  [params.gallery]
    enable = true
    width = '300'
    layout = "grid"

  [params.dateform]
    CopyrightDate = "2006"
    LongDate = "2006年1月2日"
    ShortDate = "1月2日"
    NumDateShort = "2006-01-02"
    NumDateLong = "2006-01-02 15:04 -0700"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/ElofHew"

  [[params.socialLinks]]
    name = "email"
    url = "mailto:2352235176@qq.com"

  [[params.socialLinks]]
    name = "bilibili"
    url = "https://space.bilibili.com/642688364"

  [[params.socialLinks]]
    name = "telegram"
    url = "https://t.me/ElofHew"

[menu]
  [[menu.main]]
    name = "文章"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "关于"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "主站"
    url = "https://www.danevan.top"
    weight = 30
